version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8009:80"
    environment:
      - DATABASE_URL=postgresql://admin:test1234@db:5432/sentimentdbprod
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_DB=sentimentdbprod

volumes:
  postgres_data_prod:
