FROM tiangolo/uvicorn-gunicorn:python3.11-slim

RUN apt-get update && apt-get install -y netcat-traditional

COPY requirements.txt .

COPY alembic.ini /app/
COPY alembic/ /app/alembic/

RUN pip install -r requirements.txt

COPY . .
